version: '2'
services:
  jenkins:
    restart: always
    image: "{{ jenkins_docker_src }}:{{ ansible_env.JenkinsVersion | default(jenkins_version)}}"
    privileged: true
    expose:
      - "8080"
    ports:
      - "127.0.0.1:50000:50000"
      - "0.0.0.0:12345:12345"
      - "0.0.0.0:12346:12346"      
    extra_hosts:
      - "host:{{ ansible_default_ipv4.address }}"
    volumes:
      - {{ jenkins_home }}:/var/jenkins_home
      - /root/.ssh:/var/jenkins_home/.ssh
    environment:
      - JAVA_OPTS=
          -Djenkins.install.runSetupWizard=false
          -Djava.awt.headless=true
          -Dhudson.plugins.git.GitSCM.verbose=true
          -XX:+DisableExplicitGC
          -Xms1000m
          -Xmx3000m
          -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/London
          -Duser.timezone=Europe/London
          -Dhttps.protocols=TLSv1
          -Dorg.eclipse.jetty.server.Request.maxFormContentSize=5000000
          -Dhudson.plugins.parameterizedtrigger.ProjectSpecificParametersActionFactory.compatibility_mode=true
          -Dpermissive-script-security.enabled=true
          -XX:+PrintGCDetails
          -XX:+TraceClassUnloading
          -XX:+TraceClassLoading
          -XX:MaxMetaspaceSize=1g
          -XX:+CMSClassUnloadingEnabled
          -XX:+UseConcMarkSweepGC
          -Djava.rmi.server.hostname={{ ansible_default_ipv4.address }}
          -Dcom.sun.management.jmxremote.local.only=false
          -Dcom.sun.management.jmxremote.port=12345
          -Dcom.sun.management.jmxremote.rmi.port=12346
          -Dcom.sun.management.jmxremote.authenticate=false
          -Dcom.sun.management.jmxremote.ssl=false
    logging:
      driver: syslog
      options:
        tag: jenkins
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  portainer:
    restart: always
    image: "portainer/portainer"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - /var/server/config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    logging:
      driver: syslog
      options:
        tag: portainer 
 
  nginx:
    restart: always    
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - portainer
      - jenkins
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
